import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import GameInfo from '../components/GameInfo'
import styles from '../styles/Home.module.css'
import Magasin from './Magasin'
import Header from '../components/Header'

export default function Home() {

  const [idGenre, setIdGenre] = useState(0);
  const [idGame, setIdGame] = useState(0);

  console.log(idGame);

  return (

    idGame == 0 ?

      <div className={styles.container}>
        <Head>
          <title>Rawgio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={styles.main}>
          <Magasin setIdGenre={setIdGenre} idGenre={idGenre} setIdGame={setIdGame} />
        </main>
      </div>

      :

      <GameInfo idGame={idGame} setIdGame={setIdGame} />
  )
}
